# =============================================================================
## @file    TrialManager.py
#  @authors Derek Anderson
#  @date    09.19.2025
# -----------------------------------------------------------------------------
## @brief Class to generate commands and scripts to run
#    for a given trial.
# =============================================================================

import datetime
import json
import os
import pathlib
import re
import subprocess

from EICMOBOTestTools import AnaGenerator
from EICMOBOTestTools import ConfigParser
from EICMOBOTestTools import FileManager
from EICMOBOTestTools import GeometryEditor
from EICMOBOTestTools import RecGenerator
from EICMOBOTestTools import SimGenerator

class TrialManager:
    """TrialManager

    A class to generate commands and scripts to be run
    for a given trial.
    """

    def __init__(self, run, par, ana, tag = None):
        """constructor accepting arguments

        Note that if no tag is provided, then
        one will be autogenerated based on
        start time.

        Args:
          run: runtime configuration file
          par: parameter configuration file
          ana: objectives configuration file
          tag: tag to use for trial
        """
        self.tag     = self.__MakeTimeTag() if tag == None else tag
        self.cfgRun  = ConfigParser.ReadJsonFile(run)
        self.cfgPar  = ConfigParser.ReadJsonFile(par)
        self.cfgAna  = ConfigParser.ReadJsonFile(ana)
        self.geoEdit = GeometryEditor(run, self.tag)
        self.simGen  = SimGenerator(run)
        self.recGen  = RecGenerator(run)
        self.anaGen  = AnaGenerator(run, ana)

    def __MakeTimeTag(self):
       """MakeTimeTag

       Generates a tag based on current time.

       Returns:
         generated tag
       """
       time = str(datetime.datetime.now())
       time = re.sub(r'[.\-:\ ]', '', time)
       tag = f"AID2ETrial{time}"
       return tag
    


    def __DoGeometryEdits(self, params):
        """DoGeometryEdits

        Generate new geometry files.

        Args:
          params: dictionary of parameter names and current values (eg. from Ax)
        """
        trialConfig = ""
        self.geoEdit.CopyGeoToRunDir()
        for par, value in params.items():
            cfg = self.cfgPar["parameters"][par]
            if cfg["stage"] != "sim":
                continue
            else:
                self.geoEdit.EditCompact(cfg, value, self.tag)
                self.geoEdit.EditRelatedFiles(cfg, self.tag)

    def __SetRecoArgs(self, params):
        """SetRecoArgs

        Set updated reconstruction arguments.

        Args:
          params: dictionary of parameter names and current values (eg. from Ax)
        """
        self.recGen.ClearArgs()
        for par, value in params.items():

            # ignore parameters from earlier stages
            cfg = self.cfgPar["parameters"][par]
            if cfg["stage"] != "rec":
                continue
            else:
                self.recGen.AddParamToArgs(cfg, value)

    def MakeTrialScript(self, params):
        """MakeTrialScript

        Generate needed geometry files and script to run
        full sequence of trial.

        Args:
          params: dictionary of parameter names and current values (eg. from Ax)
        Returns:
          tuple of path to script and a dictionary of output files
          associated with each objective
        """

        # step 1: edit geometry files, set
        # reconstruction parameters
        self.__DoGeometryEdits(params)
        self.__SetRecoArgs(params)

        # create command to recompile geo
        recompGeo = self.geoEdit.MakeGeoRecompileCommand()
        commands  = [recompGeo]

        # if using default config, create modified
        # config with compacts updated
        if self.cfgRun["det_config"] == "epic":
            commands.append(
                self.geoEdit.MakeConfigCopyCommand(self.tag)
            )

        # create commands to set detector path, config
        commands.append(
            FileManager.MakeDetSetCommands(
                self.geoEdit.detPath,
                self.cfgRun["det_config"],
                self.tag
            )
        )

        # check for overlaps
        commands.append(
            self.geoEdit.MakeOverlapCheckCommand(self.tag)
        )

        # if an eicrecon installation is specified,
        # make command to set that
        if "eicrecon_setup" in self.cfgRun:
            setRecInstall = FileManager.MakeRecSetCommands(
                self.cfgRun["eicrecon_setup"]
            )
            commands.append(setRecInstall)

        # identify what analysis inputs are needed
        anaInputs = set()
        for anaCfg in self.cfgAna["objectives"].values():
            for inKey in anaCfg["inputs"]:
                anaInputs.add(inKey)

        # step 2: generate relevant simulation,
        # reconstruction commands
        outFiles  = dict()
        simMerges = dict()
        recMerges = dict()
        for inKey, inCfg in self.cfgRun["sim_input"].items():

            # if no objective needs input, ignore it
            if inKey not in anaInputs:
                continue

            # if there are multiple steering files,
            # loop over each
            inLoc  = inCfg["location"]
            inType = inCfg["type"]
            for inSteer in os.listdir(inLoc):

                # only consider steering files
                # (which end in .py)
                isSteer = inSteer.endswith('.py')
                if not isSteer:
                    continue

                # generate command to run simulation
                commands.append(
                    self.simGen.MakeCommand(
                        self.tag,
                        inKey,
                        inLoc,
                        inSteer,
                        inType
                    )
                )

                # now generate command to run reconstruction
                commands.append(
                    self.recGen.MakeCommand(
                        self.tag,
                        inKey,
                        inSteer
                    )
                )

            # now generate command to merge sim, reco
            # output from each individual dataset
            #   -- FIXME it would be better to have some way to
            #      1st identify what needs to be merged and then
            #      only merge that
            doSimMerge, simMerged = self.anaGen.MakeMergeCommand(self.tag, inKey, "sim")
            doRecMerge, recMerged = self.anaGen.MakeMergeCommand(self.tag, inKey, "rec")
            commands.append(doSimMerge)
            commands.append(doRecMerge)
            simMerges[inKey] = simMerged
            recMerges[inKey] = recMerged

        # grab output directory for any merging that needs
        # to be done
        outDir = self.cfgRun["out_path"] + "/" + self.tag

        # step 3: generate relevant analysis commands
        anaMerges = list()
        for anaKey, anaCfg in self.cfgAna["objectives"].items():

            # skip if objective is not an analysis
            if anaCfg["stage"] != "ana":
                continue

            # collect files for each input dataset. If no
            # inputs present, skip objective
            simInputs   = list()
            recInputs   = list()
            anaInLabels = list()
            for inKey in anaCfg["inputs"]:
                if inKey in simMerges and inKey in recMerges:
                    simInputs.append(simMerges[inKey])
                    recInputs.append(recMerges[inKey])
                    anaInLabels.append(inKey)

            anaInLabel = ""
            if len(anaInLabels) == 0:
                continue
            else:
                anaInLabels = sorted(anaInLabels)
                anaInLabel  = '_'.join(anaInLabels)

            # now generate merging commands
            simInput = ""
            if len(simInputs) == 1:
                simInput = simInputs[0]
            else:
                simInput = outDir + "/" + FileManager.MakeOutName("sim", self.tag, anaInLabel, "", "", "merge")
                if simInput not in anaMerges:
                    simMerge = "hadd -f " + simInput + " " + ' '.join(simInputs)
                    commands.append(simMerge)
                    anaMerges.append(simInput)

            recInput = ""
            if len(recInputs) == 1:
                recInput = recInputs[0]
            else:
                recInput = outDir + "/" + FileManager.MakeOutName("rec", self.tag, anaInLabel, "", "", "merge")
                if recInput not in anaMerges:
                    recMerge = "hadd -f " + recInput + " " + ' '.join(recInputs)
                    commands.append(recMerge)
                    anaMerges.append(recInput)

            # and finally generate analysis command
            command, outFile = self.anaGen.MakeCommand(self.tag,
                                                       inKey,
                                                       anaKey,
                                                       simInput,
                                                       recInput)

            # append analysis command and output file
            # to appropriate lists/dictionaries
            commands.append(command)
            outFiles[anaKey] = outFile

        # step 4: make sure run directory
        # exists for trial
        runDir = self.cfgRun["run_path"] + "/" + self.tag
        FileManager.MakeDir(runDir)

        # construct script name
        runScript = FileManager.MakeScriptName(self.tag)
        runPath   = runDir + "/" + runScript

        # compose script
        with open(runPath, 'w') as script:
            script.write("#!/bin/bash\n\n")
            script.write("set -e\n\n")
            for command in commands:
                script.write(command + "\n\n")

        # make sure script can be run
        os.chmod(runPath, 0o777)

        # return path to script
        return runPath, outFiles

    def DoTrial(self, param):
        """DoTrial

        Carries out trial by generating the relevant
        script and then running it. For each objective
        run, current parameter values will be appended
        to an output text file.

        Note that extracting objectives depends on the
        individual analyses. That functionality is
        deferred to a separate interface module.

        Args:
          param: dictionary of parameters and their current values
        Returns:
          dictionary of output files
        """

        # create and run script
        script, outFiles = self.MakeTrialScript(param)
        process = subprocess.run([self.cfgRun["eic_shell"], "--", script])

        # write out values of parameters for later
        # analysis
        #   --> if parameters generated overlap
        #       (return code 9), punish with
        #       objectives above or below
        #       threshold
        for anaKey, anaOut in outFiles.items():
            anaPath = pathlib.Path(anaOut)
            anaJson = anaPath.with_suffix('.json')
            with open(anaJson, 'r+') as anaj:
                anaDat = json.load(anaj)
                if process.returncode == 9:
                    anaDat[anaKey] = self.anaGen.GetDummyValue(anaKey)
                outDat = anaDat | param
                anaj.seek(0)
                json.dump(outDat, anaj)

        # return relevant output files
        return outFiles

# end =========================================================================
